<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6PthJL0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6PthJL0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6PthJL0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6PthJL0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6PthJL0\App_KernelDevDebugContainer([
    'container.build_hash' => '6PthJL0',
    'container.build_id' => 'ad1dfa70',
    'container.build_time' => 1659106285,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6PthJL0');
